version: '3.7'

services:
  web:
    build: .
    depends_on:
      - db
    volumes:
      - .:/app
    ports:
        - "8000:8000"
    env_file:
      - .env

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    env_file:
      - .env

volumes:
    postgres_data:
